### ISSUE TITLE
MockFile.ReadAllText throws NullReferenceException on non existing file

### ISSUE THREAD

**Issue by derpflanz** [TestableIO/System.IO.Abstractions#758] opened 2021-11-05 12:27 UTC
**Describe the bug**
MockFile.ReadAllText throws NullReferenceException on non existing file. I expect FileNotFoundException

**To Reproduce**
var fileSystem = new MockFileSystem();
fileSystem.File.ReadAllText("nonexisting file", Encoding.UTF8);
--> A NullReferenceException is thrown

**Expected behavior**
--> A FileNotFoundException is thrown

**Comment by fgreinacher** [comment] 2021-11-05 12:40
Thanks for reporting!

**Comment by tuan-tu-tran** [comment] 2022-02-24 21:59
I can't reproduce this issue: the given code snippet produces the expected behaviour.

Also there's already a test that ensures it:
[MockFile_ReadAllLines_NotExistingFile_ThrowsCorrectFileNotFoundException](https://github.com/TestableIO/System.IO.Abstractions/blob/ced2f2b8e2a251cd87a0ee1049d19c947d0edfe3/tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllLinesTests.cs#L60)

It was added by #427

**Comment by fgreinacher** [comment] 2022-02-28 08:00
> I can't reproduce this issue: the given code snippet produces the expected behaviour.
> 
> Also there's already a test that ensures it: [MockFile_ReadAllLines_NotExistingFile_ThrowsCorrectFileNotFoundException](https://github.com/TestableIO/System.IO.Abstractions/blob/ced2f2b8e2a251cd87a0ee1049d19c947d0edfe3/tests/System.IO.Abstractions.TestingHelpers.Tests/MockFileReadAllLinesTests.cs#L60)
> 
> It was added by #427

@derpflanz Could you please verify with the latest version? If the issue still occurs could you provide some more information about your environment?

**Comment by derpflanz** [comment] 2022-03-02 10:22
@fgreinacher I tried to find the sport and reproduce, but it has been a few months and our code continued to evolve :).

It seems like it works fine, so I guess an update fixed it.

**Comment by fgreinacher** [comment] 2022-03-02 21:38
Thanks for checking again, I guess we can close this then.

**Closed** 2022-03-02 21:38 UTC
Labels: type: bug, state: ready, area: testinghelpers, flag: good-first-issue
