### ISSUE TITLE
IFile.Create has different return type than File.Create

### ISSUE THREAD

**Issue by Heldenkrieger01** [TestableIO/System.IO.Abstractions#779] opened 2021-12-14 10:23 UTC
**Describe the bug**
The `IFile.Create()` method returns a `Stream`, but the "original" `File.Create()` returns a `FileStream`. This is important, because the `FileStream` contains the `Name`-property with the files name.

**Expected behavior**
`IFile.Create()` returns a `FileStream`.

**Comment by fgreinacher** [comment] 2021-12-17 12:15
This is more or less by design, because `FileStream` relies on the real file system.

We could return a custom subclass of `Stream` that adds the `Name` property.

What do you think about this?

**Comment by Heldenkrieger01** [comment] 2021-12-23 15:45
That would be great, especially for people like me, that move to Abstractions with existing code.

**Comment by fgreinacher** [comment] 2022-01-06 12:02
Cool, so let's make this as ready and discuss details in a PR, once somebody finds the time to work on this 👍

**Comment by vbreuss** [comment] 2023-04-16 17:47
I think this issue can be closed, as the `FileSystemStream` was implemented in #906 ...
Do you agree, @Heldenkrieger01 ?

**Comment by fgreinacher** [comment] 2023-04-19 17:38
I'm closing this. Feel free to reopen if needed!

**Closed** 2023-04-19 17:38 UTC
Labels: type: enhancement, state: ready to pick, area: core, flag: good-first-issue
